### ISSUE TITLE
`error: attribute 'fetchPypi' missing`

### ISSUE THREAD

**Issue by dominikh** [nix-community/nix-init#15]
Running nix-init against https://pypi.org/project/countryguess/ fails:

```
Enter url
❯ https://pypi.org/project/countryguess/
Enter tag or revision (defaults to 0.2.1)
❯ 0.2.1
Enter version
❯ 0.2.1
Enter pname
❯ countryguess
Error: command exited with exit status: 1
stdout:

stderr:
error: attribute 'fetchPypi' missing

       at «string»:1:44:

            1| let pname="countryguess";version="0.2.1";in(import<nixpkgs>{}).fetchPypi {
             |                                            ^
            2|     inherit pname version;
```

A cursory glance suggests that this happens in main.rs:282 because it assumes that `src_expr` makes sense relative to nixpkgs. But for fetchPypi (and presumably fetchCrate, too?) while the argument to the generated nix function will be called `fetchPypi`, it'll be provided by `<nixpkgs>.python3Packages.fetchPypi`.

**Comment by figsoda** [comment]
the error should be fixed by https://github.com/nix-community/nix-init/commit/ca5b1fbf92c3e4dd27f8c97dd21d4da4cb04cafb, I will keep this around until (probably a little after) 23.05 comes out, as I only plan to support the latest stable channel

The generated package still wouldn't work with nixpkgs 22.11, since there is no way to customize the output based on the version of nixpkgs targeted, but you can just put a `python3.pkgs.` before `fetchPypi` if you want it to work with nixpkgs 22.11

**Comment by dominikh** [comment]
Can confirm that this fixes it.

If I'm not mistaken, the generated package should work with nixpkgs 22.11, because fetchPypi is also an argument and filled in by callPackage? At least that's my empirical result.

**Comment by figsoda** [comment]
It works with `python3.pkgs.callPackage`, but fails with this error with the top-level `callPackage`

```
error: Function called without required argument "fetchPypi" at <path>:<position>
```

I will go ahead and close this since the original issue has been fixed

**Comment by tmarkov** [comment]
Happens to me still with `nix-init 0.3.0`
