### ISSUE TITLE
Selection does not work under zsh.

### ISSUE THREAD

**Issue by DaKingof** [nix-community/nix-init#165]
When attempting to select the method used with tab it only comes up with option 0 on zsh. When I try typing in another option it just says hit tab to see options. The only thing I can do is hit enter. Typing any number 0-5 does nothing but tell me to hit tab.

**Comment by figsoda** [comment]
This is probably not an issue with zsh. There might be only 1 option if the only thing showing up is option 0, and nix-init tells you to press tab when you are not picking an available option, and pressing enter commits the selection.

I agree this is not the most intuitive interface, which is why I am planning on a redesign for nix-init's UI. Feel free to drop a comment in #72 on what you think would be a better alternative.

**Comment by DaKingof** [comment]
It goes through if I hit enter without selecting anything. But when I select zero it tells me to select 0-5. Same with any other number. I'm not sure what would be better, but I'll definitely test when you've decided on a new interface to see if it works then. Thank you.

**Comment by figsoda** [comment]
> But when I select zero it tells me to select 0-5

hmm, that sounds like a bug to me, which repository are you working with? I'll see if I can reproduce this

**Comment by DaKingof** [comment]
I'm on unstable. If you want my nixconfig I can send it to you.

**Comment by figsoda** [comment]
ah, by repository I mean what is the URL of the program you are trying to package, i.e. what did you put in when nix-init asked `Enter url`

**Comment by DaKingof** [comment]
Ohh! I was trying out https://github.com/btobolaski/text-generation-webui to locally host some LLM for testing.

**Comment by DaKingof** [comment]
![image](https://github.com/nix-community/nix-init/assets/31186364/bb80e19d-490d-4543-a03e-9e197511f302)

This is what I see here.

**Comment by figsoda** [comment]
This is what I got too, what happens if you press enter and then enter here

**Comment by DaKingof** [comment]
It creates the deviation, but it's a python project so it's incorrect.

```
{ lib
, stdenv
, fetchFromGitHub
}:

stdenv.mkDerivation rec {
  pname = "text-generation-webui";
  version = "installers";

  src = fetchFromGitHub {
    owner = "oobabooga";
    repo = "text-generation-webui";
    rev = version;
    hash = "sha256-18+Ed2+oNsPDT9VZgCCpXFW9TEokhJpoQzTVllCS7Jw=";
  };

  meta = with lib; {
    description = "A gradio web UI for running Large Language Models like LLaMA, llama.cpp, GPT-J, Pythia, OPT, and GALACTICA";
    homepage = "https://github.com/oobabooga/text-generation-webui";
    license = licenses.agpl3Only;
    maintainers = with maintainers; [ ];
  };
}
```

**Comment by figsoda** [comment]
This is expected since it doesn't use a standard python packaging method. nix-init is only able to detect the python if the repository contains `setup.py` or `pyproject.toml`, this is also the only way `buildPythonApplication` from nixpkgs can work AFAIK. So if you were to manually package it, you would probably also need to use `stdenv.mkDerivation`

**Comment by DaKingof** [comment]
I see. That makes sense...so it's looking at the package and determining the other options aren't valid based on the file structure? So not a bug?

I guess I'll have to figure out how to manually make this deriviation from here then.

**Comment by figsoda** [comment]
> That makes sense...so it's looking at the package and determining the other options aren't valid based on the file structure? 

Yep

**Comment by DaKingof** [comment]
Alright. Thank you very much for the help/assistance and your work on this project. I'll close this now since it's not a bug.

Looking forward to the redesign and where this goes! Have a wonderful weekend.
